### PR TITLE
Release 10.0.0

### PR DESCRIPTION
**Pull request by Baggerone**
Change Google Analytics env vars to move to GA4.
Remove serverless IAM policy from CD user. A separate user was added as Terraform configuration in [silinternational/serverless-mfa-api](https://github.com/silinternational/serverless-mfa-api) as of version 2.3.

---------------

## Removed from 000-core main.tf
The AWS IAM user policy giving permissions to the CE serverless user, since the serverless mfa code 
has moved to a different repo.
A separate user was added as Terraform configuration in [silinternational/serverless-mfa-api](https://github.com/silinternational/serverless-mfa-api) as of version 2.3.

## Removed from 040-id-broker/vars.tf
`ga_tracking_id` (not used by Google Analytics 4)

## Added to 040-id-broker/vars.tf
`ga_api_secret`  -  The Google Analytics 4 API secret for the data stream (e.g. aB-abcdef7890123456789)
`ga_measurement_id` - The Google Analytics data stream id (e.g. G-ABCDE67890)

### CODE REVIEW

**Comment by Baggerone** [comment]
> Regarding moving the serverless CI/CD user from 000-core to the mfa-api, is that also a breaking change? What needs to happen for the CI/CD process for that to continue working (e.g. new AWS IAM user created via mfa-api's terraform, update CI/CD variables to use that new AWS Key/Secret, ... anything else)?

@Schparky, do you have answers for Matt on these questions?

**Comment by Baggerone** [comment]
> ... but it does look like it would be a breaking changes ...

@forevermatt I'm not sure what you're implying by this. Do you mean it should be `5.0.0` rather than just `4.6.0`?

**Comment by forevermatt** [comment]
> > Regarding moving the serverless CI/CD user from 000-core to the mfa-api, is that also a breaking change? What needs to happen for the CI/CD process for that to continue working (e.g. new AWS IAM user created via mfa-api's terraform, update CI/CD variables to use that new AWS Key/Secret, ... anything else)?
> 
> @Schparky, do you have answers for Matt on these questions?

Whatever those changes are (if any), it would probably be worth documenting them in the release notes for this (presumably 5.0.0) version of idp-in-a-box, just to help us / other users of this repo make the necessary changes when the time comes.

**Review by Schparky — APPROVED** [review]

**Comment by Schparky** [comment]
> I think this looks fine, but it does look like it would be a breaking changes, since the required variable inputs are changing.
> 
> Regarding moving the serverless CI/CD user from 000-core to the mfa-api, is that also a breaking change? What needs to happen for the CI/CD process for that to continue working (e.g. new AWS IAM user created via mfa-api's terraform, update CI/CD variables to use that new AWS Key/Secret, ... anything else)?
> 
> Thanks for getting this rolling (and keeping it moving forward). +1

From a stricter point of view, yes, I think this could be considered a major change. But then, most changes are major because this has such a large "API footprint". I'm fine with making this 10.0.0, but would be fine with 9.6.0 as well.

Nothing remains to be done for the IAM change. The separate user for serverless deployment was created at the time of the serverless-mfa-api update. All this does is remove that policy from the CD user created for the IDP.

**Pull request merged**
